#!/bin/bash

dir=~/dotfiles
olddir=~/dotfiles_old
files="minttyrc mutt oh-my-zsh tmux.conf todo.cfg vim vimrc zsh-aliases zshrc"

echo "Creating $olddir for backup"
mkdir -p $olddir
echo "Done!"

cd $dir
for file in $files; do
	echo "Moving any existing dotfiles from ~ to $olddir"
	mv ~/.$file $olddir/
	echo "Creating symlink to $file in home dir"
	ln -s $dir/$file ~/.$file
done
