#!/bin/bash

if [[ "$OSTYPE" == "cygwin" ]]; then
	echo "installing apt-cyg..."
	if [ ! -d "~/bin" ]; then
		mkdir ~/bin
	fi
	cd ~/bin
	wget -q https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg
	chmod +x apt-cyg
	export PATH=~/bin:$PATH
	cd ~/
fi

echo "installing packages..."
if [[ "$OSTYPE" == "cygwin" ]]; then
	apt-cyg install curl git vim zsh mutt tmux
else
	sudo apt-get install curl git vim zsh mutt tmux
fi

echo "backing up old dotfiles..."
dir=~/dotfiles
olddir=~/dotfiles_old
files="minttyrc mutt tmux.conf todo.cfg vim vimrc zsh-aliases zshrc"

echo "Creating $olddir for backup"
mkdir -p $olddir
echo "Done!"

echo "installing oh my zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "installing poweline fonts..."
git clone https://github.com/powerline/fonts.git
if [[ "$OSTYPE" == "cygwin" ]]; then
	# run powershell install
	if [[ "$(powershell Get-ExecutionPolicy)" == "RemoteSigned" ]]; then
		powershell -File fonts/install.ps1
	else
		echo "Can't install fonts. Need to run the following command in Powershell:"
		echo "Set-ExecutionPolicy RemoteSigned"
		echo "Then run the install.ps1 script in fonts folder."
	fi
else
	fonts/install.sh
fi

echo "installing todo.txt..."
mkdir ~/bin
cd ~/bin
wget -q https://raw.githubusercontent.com/ginatrapani/todo.txt-cli/master/todo.sh
chmod +x todo.sh
cd ~/
echo "Symlinking todo.txt to Dropbox dir"
ln -s ~/Dropbox/.todo .todo
mkdir ~/.todo.actions.d
cd ~/.todo.actions.d
wget -q http://github.com/the1ts/todo.txt-plugins/raw/master/actions/projectview/projectview
chmod +x projectview
cd ~/

cd $dir
for file in $files; do
	echo "Moving any existing dotfiles from ~/.$file to $olddir"
	mv ~/.$file $olddir/
	echo "Creating symlink to $file in home dir"
	ln -s $dir/$file ~/.$file
done

echo "Setting up mutt..."
cp /usr/share/doc/mutt/examples/gpg.rc ~/.gpg.rc
ln -s ~/Dropbox/userinfo.muttrc ~/.mutt/userinfo.muttrc
touch ~/.mutt/subscriptions.muttrc

# Needs to be done after .vim has been symlinked
echo "installing vim plugins..."
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
